name: 'Stage'
description: 'Stage build'
inputs:
  tarball-artifact-name:
    description: Name of the artifact used to store stage progress
    default: build-artifact
    required: false
  tarball-file-name:
    description: File name (on disk) of the artifact used to store stage progress
    default: artifacts.7z
    required: false
  tarball-root:
    description: Base directory which the stage progress tarball's file paths are relative to
    required: true
  tarball-pattern:
    description: Patterns (separated by newline) of files to add to the progress tarball. By default stores everything under 'tarball-root'
    required: false
  before-run:
    description: Non-timeout newline-separated commands to execute before 'run'. The execution duration of these commands will reduce the length of 'timeout'
    required: false
  run:
    description: Newline-separated commands to execute with a timeout
    required: true
  after-run:
    description: Non-timeout newline-separated commands to execute after 'run'
    required: false
  cwd:
    description: Working directory for the script. Also where relative paths passed to other inputs are resolved from
    required: false
  timeout:
    description: The timeout for all commands to finish executing, in milliseconds. Default to 3 hours and 30 minutes.
    required: false
    default: '12600000' # 3.5 * 60 * 60 * 1000
  inputs:
    description: String to pass to STDIN of commands
    required: false
  input-encoding:
    description: Encoding for STDIN, defaults to UTF-8
    default: utf-8
    required: true
  ignore-exit-codes:
    description: Comma-separated list of numeric exit codes to treat as timeouts if returned from spawned processes
    required: false
  fail-on-stderr:
    description: Whether to fail if output to stderr. Defaults to false
    required: false
    default: 'false'
  load-tarball-artifact-if-exists:
    description: Whether to load the progress tarball if found one with 'tarball-artifact-name' in the current workflow
    required: false
    default: 'true'
  save-tarball-artifact:
    description: Whether to save the progress tarball if commands do not finish execution before the timeout is reached
    required: false
    default: 'true'
  shell:
    description: "The shell to run the command as; one of 'none', 'cmd', 'pwsh', 'python', 'node'. If 'none', runs each line raw as a separate command"
    required: false
    default: none
  key:
    description: Used for splitting timed actions across multiple steps, while inheriting the same timeout. All stage actions with the same key within a job \
      will timeout when the timeout for the first action with a key is reached.
    required: false
outputs:
  results-per-command:
    value: ${{ steps.step.outputs.results-per-command }}
    description: JSON-stringified array of exit codes ordered per command (each line in 'run'), or a 'timeout' instead of an entry if execution timed out.
  outcome:
    value: ${{ steps.step.outputs.outcome }}
    description: "One of: 'failure', 'timeout', 'success'"
  before-run-outcome:
    value: ${{ steps.step.outputs.before-run-outcome }}
    description: "One of: 'failure', 'timeout', 'success', 'skipped'"
  after-run-outcome:
    value: ${{ steps.step.outputs.after-run-outcome }}
    description: "One of: 'failure', 'timeout', 'success', 'skipped'"
runs:
  using: composite
  steps:
    - id: step
      shell: pwsh
      run: |
        $env:INPUT_tarball-artifact-name = ${{ inputs.tarball-artifact-name }}
        $env:INPUT_tarball-file-name = ${{ inputs.tarball-file-name }}
        $env:INPUT_tarball-root = ${{ inputs.tarball-root }}
        $env:INPUT_tarball-pattern = ${{ inputs.tarball-pattern }}
        $env:INPUT_before-run = ${{ inputs.before-run }}
        $env:INPUT_run = ${{ inputs.run }}
        $env:INPUT_after-run = ${{ inputs.after-run }}
        $env:INPUT_cwd = ${{ inputs.cwd }}
        $env:INPUT_timeout = ${{ inputs.timeout }}
        $env:INPUT_inputs = ${{ inputs.inputs }}
        $env:INPUT_input-encoding = ${{ inputs.input-encoding }}
        $env:INPUT_ignore-exit-codes = ${{ inputs.ignore-exit-codes }}
        $env:INPUT_fail-on-stderr = ${{ inputs.fail-on-stderr }}
        $env:INPUT_load-tarball-artifact-if-exists = ${{ inputs.load-tarball-artifact-if-exists }}
        $env:INPUT_save-tarball-artifact = ${{ inputs.save-tarball-artifact }}
        $env:INPUT_shell = ${{ inputs.shell }}
        $env:INPUT_key = ${{ inputs.key }}
        . $env:GITHUB_ACTION_PATH/index.ps1
