name: "Image Actions"
author: "Calibre"
description: "Compresses Images for the Web"

inputs:
  githubToken:
    description: "GitHub Token"
    required: true

  jpegQuality:
    description: "JPEG quality level"
    required: false
    default: "80"

  jpegProgressive:
    description: "Use progressive (interlaced) scan for JPEG"
    required: false
    default: "false"

  pngQuality:
    description: "PNG quality level"
    required: false
    default: "80"

  webpQuality:
    description: "WEBP quality level"
    required: false
    default: "80"

  ignorePaths:
    description: "Paths to ignore during search"
    required: false
    default: "node_modules/**"

  compressOnly:
    description: "Images will be compressed. No commit, or comments will be added to your Pull Request"
    required: false
    default: "false"

  commitName:
    description: ''
    required: false
    default: ''

  commitEmail:
    description: ''
    required: false
    default: ''

  location:
    description: 'Root path to optimize images in'
    required: false
    default: ''

outputs:
  markdown:
    description: "Output param used to store the Markdown summary for subsequent actions to use"

runs:
  using: "docker"
  image: "docker://ghcr.io/uwx/actions/calibre-image-actions:main"

branding:
  icon: "image"
  color: "green"
