name: multistep CI

on:
  push:
    branches: [ "main" ]

    paths:
      - ".github/workflows/multistep.yml"
      - "multistep/**"

  pull_request:
    branches: [ "main" ]

    paths:
      - "multistep/**"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - uses: pnpm/action-setup@v2
      with:
        version: 8

    - run: pnpm install

    - run: pnpm install
      working-directory: multistep

    - run: rollup -c --bundleConfigAsCjs
      working-directory: multistep

    - run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git config pull.rebase true

        git add . && \
        git commit -m"Automated compile multistep" && \
        git pull && \
        git push

        exit 0
      if: github.event_name == 'push'